# NumPy Tutorial
## NumPy Introduction
## NumPy Getting Started

In [12]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr.ndim)

3


## NumPy Array Indexing

In [13]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [28]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print('2nd element on 1st row: ', arr[:,:,1])

2nd element on 1st row:  [[ 2  5]
 [ 8 11]]


## NumPy Array Slicing

In [34]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


In [39]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## NumPy Data Types

## NumPy Array Copy vs View

In [40]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [41]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [42]:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## NumPy Array Shape

In [44]:
import numpy as np 

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [45]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## NumPy Array Reshape

In [46]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [50]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [51]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## NumPy Array Iterating

In [53]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [54]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [55]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [56]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [58]:
import numpy as np

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [59]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [60]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])

for x  in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [64]:
import numpy as np

arr = np.array([1,2,3,4])

for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [65]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Joining Array

In [66]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [69]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [73]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [74]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [75]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## NumPy Splitting Array

In [76]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [77]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [78]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [79]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [80]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [81]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [82]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Arrays

In [83]:
import numpy as np

arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [85]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [86]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [87]:
import numpy as np

arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)


1


In [88]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [89]:
import numpy as np

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


## NumPy Sorting Arrays

In [90]:
import numpy as np

arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [91]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [92]:
import numpy as np

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [93]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## NumPy Filter Array

In [94]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [95]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [96]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [97]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
